/* ═══════════════════════════════════════════════════════════
   JamZia™ Grade Progression Engine
   Nursery School → Doctoral Programs
   "Everyone starts at Nursery. No one skips the Castle."
   ═══════════════════════════════════════════════════════════ */

export interface GradeLevel {
  id: string;
  name: string;
  shortName: string;
  sequence: number;
  phase: 'early' | 'elementary' | 'middle' | 'high' | 'college' | 'postgrad';
  phaseLabel: string;
  testsRequired: number;
  passRate: number;
  phonicsMasteryRequired: boolean;
  castleGate: string;
  castleCreature: string;
  skillsEarned: string[];
  jamziaCertification: string | null;
  nextGradeId: string | null;
  prevGradeId: string | null;
  description: string;
  realWorldValue: string;
  creditHours: number; // Credit hours for this grade
  tuition: number; // Brick cost to enroll
}

/* ── Full Grade Ladder ── */
export const GRADE_LEVELS: GradeLevel[] = [
  // === EARLY CHILDHOOD ===
  {
    id: 'nursery',
    name: 'Nursery School',
    shortName: 'Nursery',
    sequence: 0,
    phase: 'early',
    phaseLabel: 'Early Childhood',
    testsRequired: 3,
    passRate: 60,
    phonicsMasteryRequired: false,
    castleGate: 'The Garden Gate',
    castleCreature: 'Buddy the Puppy',
    skillsEarned: ['Letter Recognition', 'Sound Basics', 'Color Identification'],
    jamziaCertification: null,
    nextGradeId: 'preschool',
    prevGradeId: null,
    description: 'First steps on Cotton Brick Road. Learn your ABCs through AR play.',
    realWorldValue: 'Foundation for all future reading and communication skills.',
    creditHours: 3,
    tuition: 0,
  },
  {
    id: 'preschool',
    name: 'Pre-School',
    shortName: 'Pre-K',
    sequence: 1,
    phase: 'early',
    phaseLabel: 'Early Childhood',
    testsRequired: 4,
    passRate: 65,
    phonicsMasteryRequired: false,
    castleGate: 'The Sandbox Gate',
    castleCreature: 'Echo the Dolphin',
    skillsEarned: ['Vowel Sounds', 'Rhyme Recognition', 'Basic Counting'],
    jamziaCertification: null,
    nextGradeId: 'kindergarten',
    prevGradeId: 'nursery',
    description: 'Build phonemic awareness. Every sound is a brick on your road.',
    realWorldValue: 'Prepares for kindergarten readiness assessments.',
    creditHours: 3,
    tuition: 0,
  },
  {
    id: 'kindergarten',
    name: 'Kindergarten',
    shortName: 'Kinder',
    sequence: 2,
    phase: 'early',
    phaseLabel: 'Early Childhood',
    testsRequired: 5,
    passRate: 70,
    phonicsMasteryRequired: false,
    castleGate: 'The Rainbow Gate',
    castleCreature: 'Buzz the Bee',
    skillsEarned: ['Sight Words Set 1', 'Blending CVC', 'Number Sense'],
    jamziaCertification: 'JamZia Early Reader Badge',
    nextGradeId: 'grade1',
    prevGradeId: 'preschool',
    description: 'Read your first sentences. The road gets brighter from here.',
    realWorldValue: 'Early literacy predicts long-term academic success.',
    creditHours: 3,
    tuition: 0,
  },

  // === ELEMENTARY ===
  {
    id: 'grade1',
    name: 'First Grade',
    shortName: '1st',
    sequence: 3,
    phase: 'elementary',
    phaseLabel: 'Elementary School',
    testsRequired: 6,
    passRate: 70,
    phonicsMasteryRequired: true,
    castleGate: 'The Pencil Gate',
    castleCreature: 'Athena the Owl',
    skillsEarned: ['Digraphs SH/CH/TH', 'Decoding Strategies', 'Sentence Writing'],
    jamziaCertification: null,
    nextGradeId: 'grade2',
    prevGradeId: 'kindergarten',
    description: 'Mrs. Cotton\'s phonics method in full effect. Decode anything.',
    realWorldValue: 'First grade reading level is the strongest predictor of graduation.',
    creditHours: 3,
    tuition: 0,
  },
  {
    id: 'grade2',
    name: 'Second Grade',
    shortName: '2nd',
    sequence: 4,
    phase: 'elementary',
    phaseLabel: 'Elementary School',
    testsRequired: 6,
    passRate: 70,
    phonicsMasteryRequired: true,
    castleGate: 'The Bookmark Gate',
    castleCreature: 'Sage the Elephant',
    skillsEarned: ['Long Vowels', 'R-Controlled Vowels', 'Comprehension Basics'],
    jamziaCertification: null,
    nextGradeId: 'grade3',
    prevGradeId: 'grade1',
    description: 'Read to learn, not just learn to read. The shift happens here.',
    realWorldValue: 'Transition from learning-to-read to reading-to-learn.',
    creditHours: 3,
    tuition: 0,
  },
  {
    id: 'grade3',
    name: 'Third Grade',
    shortName: '3rd',
    sequence: 5,
    phase: 'elementary',
    phaseLabel: 'Elementary School',
    testsRequired: 7,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Dictionary Gate',
    castleCreature: 'Ink the Octopus',
    skillsEarned: ['Multisyllabic Words', 'Context Clues', 'Paragraph Writing'],
    jamziaCertification: 'JamZia Independent Reader',
    nextGradeId: 'grade4',
    prevGradeId: 'grade2',
    description: 'The year everything clicks. Complex texts become your playground.',
    realWorldValue: 'Third grade proficiency correlates with career earnings.',
    creditHours: 3,
    tuition: 0,
  },
  {
    id: 'grade4',
    name: 'Fourth Grade',
    shortName: '4th',
    sequence: 6,
    phase: 'elementary',
    phaseLabel: 'Elementary School',
    testsRequired: 7,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Chapter Gate',
    castleCreature: 'Drakon the Dragon',
    skillsEarned: ['Greek/Latin Roots', 'Text Structure', 'Research Skills'],
    jamziaCertification: null,
    nextGradeId: 'grade5',
    prevGradeId: 'grade3',
    description: 'Longer books, bigger worlds. You are a reader now.',
    realWorldValue: 'Research skills begin — foundation for all academic writing.',
    creditHours: 3,
    tuition: 0,
  },
  {
    id: 'grade5',
    name: 'Fifth Grade',
    shortName: '5th',
    sequence: 7,
    phase: 'elementary',
    phaseLabel: 'Elementary School',
    testsRequired: 8,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Essay Gate',
    castleCreature: 'Aurelius the Bull',
    skillsEarned: ['Figurative Language', 'Argument Basics', 'Presentation Skills'],
    jamziaCertification: 'JamZia Elementary Scholar',
    nextGradeId: 'grade6',
    prevGradeId: 'grade4',
    description: 'Make your case. Write to persuade. The road demands voice.',
    realWorldValue: 'Argumentation and presentation skills for middle school.',
    creditHours: 3,
    tuition: 0,
  },

  // === MIDDLE SCHOOL ===
  {
    id: 'grade6',
    name: 'Sixth Grade',
    shortName: '6th',
    sequence: 8,
    phase: 'middle',
    phaseLabel: 'Middle School',
    testsRequired: 8,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Seminar Gate',
    castleCreature: 'Smash the Shrimp',
    skillsEarned: ['Critical Analysis', 'Citation Basics', 'Algebra Foundations'],
    jamziaCertification: null,
    nextGradeId: 'grade7',
    prevGradeId: 'grade5',
    description: 'Middle school begins. Analysis replaces memorization.',
    realWorldValue: 'Critical thinking foundation for all secondary education.',
    creditHours: 4,
    tuition: 10,
  },
  {
    id: 'grade7',
    name: 'Seventh Grade',
    shortName: '7th',
    sequence: 9,
    phase: 'middle',
    phaseLabel: 'Middle School',
    testsRequired: 8,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Debate Gate',
    castleCreature: 'Viridia the Frog',
    skillsEarned: ['Socratic Dialogue', 'Scientific Method', 'Pre-Algebra'],
    jamziaCertification: null,
    nextGradeId: 'grade8',
    prevGradeId: 'grade6',
    description: 'Defend your ideas. Science meets rhetoric on the road.',
    realWorldValue: 'Debate and scientific reasoning for high school prep.',
    creditHours: 4,
    tuition: 10,
  },
  {
    id: 'grade8',
    name: 'Eighth Grade',
    shortName: '8th',
    sequence: 10,
    phase: 'middle',
    phaseLabel: 'Middle School',
    testsRequired: 10,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Graduation Gate',
    castleCreature: 'Arachne the Spider',
    skillsEarned: ['Advanced Composition', 'Geometry', 'Civic Literacy'],
    jamziaCertification: 'JamZia Middle School Graduate',
    nextGradeId: 'grade9',
    prevGradeId: 'grade7',
    description: 'Middle school graduation. The road forks — choose your path wisely.',
    realWorldValue: 'High school readiness. Complete middle school equivalency.',
    creditHours: 4,
    tuition: 10,
  },

  // === HIGH SCHOOL ===
  {
    id: 'grade9',
    name: 'Ninth Grade — Freshman',
    shortName: 'Freshman',
    sequence: 11,
    phase: 'high',
    phaseLabel: 'High School',
    testsRequired: 8,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Auditorium Gate',
    castleCreature: 'Leo the Lion',
    skillsEarned: ['Literary Analysis', 'Biology Foundations', 'Algebra II'],
    jamziaCertification: null,
    nextGradeId: 'grade10',
    prevGradeId: 'grade8',
    description: 'High school begins. Four years to build your transcript.',
    realWorldValue: 'High school diploma equivalency path begins here.',
    creditHours: 5,
    tuition: 15,
  },
  {
    id: 'grade10',
    name: 'Tenth Grade — Sophomore',
    shortName: 'Sophomore',
    sequence: 12,
    phase: 'high',
    phaseLabel: 'High School',
    testsRequired: 8,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Laboratory Gate',
    castleCreature: 'Drakon the Dragon',
    skillsEarned: ['Chemistry', 'World Literature', 'Trigonometry'],
    jamziaCertification: null,
    nextGradeId: 'grade11',
    prevGradeId: 'grade9',
    description: 'Sophomore year. Depth over breadth. Specialization begins.',
    realWorldValue: 'Standardized test preparation. Career exploration.',
    creditHours: 5,
    tuition: 15,
  },
  {
    id: 'grade11',
    name: 'Eleventh Grade — Junior',
    shortName: 'Junior',
    sequence: 13,
    phase: 'high',
    phaseLabel: 'High School',
    testsRequired: 10,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Thesis Gate',
    castleCreature: 'Aurelius the Bull',
    skillsEarned: ['AP-Level Content', 'Research Writing', 'Pre-Calculus'],
    jamziaCertification: null,
    nextGradeId: 'grade12',
    prevGradeId: 'grade10',
    description: 'Junior year — the hardest climb. Colleges are watching.',
    realWorldValue: 'College entrance exam readiness. Scholarship eligibility.',
    creditHours: 5,
    tuition: 15,
  },
  {
    id: 'grade12',
    name: 'Twelfth Grade — Senior',
    shortName: 'Senior',
    sequence: 14,
    phase: 'high',
    phaseLabel: 'High School',
    testsRequired: 12,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Diploma Gate',
    castleCreature: 'Leo the Lion',
    skillsEarned: ['Capstone Project', 'Calculus', 'Civics & Economics'],
    jamziaCertification: 'JamZia High School Diploma Equivalent',
    nextGradeId: 'college1',
    prevGradeId: 'grade11',
    description: 'Senior year. Finish strong. Your diploma awaits at the Castle.',
    realWorldValue: 'High school equivalency for employment and college admission.',
    creditHours: 5,
    tuition: 15,
  },

  // === COLLEGE ===
  {
    id: 'college1',
    name: 'College — Freshman',
    shortName: 'College Fr.',
    sequence: 15,
    phase: 'college',
    phaseLabel: 'College',
    testsRequired: 10,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Lecture Hall Gate',
    castleCreature: 'Athena the Owl',
    skillsEarned: ['Academic Writing', 'Introductory Programming', 'Statistics'],
    jamziaCertification: null,
    nextGradeId: 'college2',
    prevGradeId: 'grade12',
    description: 'College begins. Self-directed learning on the Brick Road.',
    realWorldValue: 'Foundation for accredited degree transfer. Job-ready skills.',
    creditHours: 6,
    tuition: 25,
  },
  {
    id: 'college2',
    name: 'College — Sophomore',
    shortName: 'College So.',
    sequence: 16,
    phase: 'college',
    phaseLabel: 'College',
    testsRequired: 10,
    passRate: 75,
    phonicsMasteryRequired: true,
    castleGate: 'The Library Gate',
    castleCreature: 'Sage the Elephant',
    skillsEarned: ['Data Structures', 'Research Methods', 'Public Speaking'],
    jamziaCertification: null,
    nextGradeId: 'college3',
    prevGradeId: 'college1',
    description: 'Sophomore year. Declare your major. The road narrows.',
    realWorldValue: 'Internship-ready skills. Portfolio development.',
    creditHours: 6,
    tuition: 25,
  },
  {
    id: 'college3',
    name: 'College — Junior',
    shortName: 'College Jr.',
    sequence: 17,
    phase: 'college',
    phaseLabel: 'College',
    testsRequired: 12,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Internship Gate',
    castleCreature: 'Arachne the Spider',
    skillsEarned: ['Advanced Algorithms', 'Project Management', 'Industry Specialization'],
    jamziaCertification: null,
    nextGradeId: 'college4',
    prevGradeId: 'college2',
    description: 'Junior year. Industry-ready projects. The Castle nears.',
    realWorldValue: 'Job interview preparation. Real-world project portfolio.',
    creditHours: 6,
    tuition: 25,
  },
  {
    id: 'college4',
    name: 'College — Senior',
    shortName: 'College Sr.',
    sequence: 18,
    phase: 'college',
    phaseLabel: 'College',
    testsRequired: 14,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Commencement Gate',
    castleCreature: 'Leo the Lion',
    skillsEarned: ['Capstone Design', 'Thesis Defense', 'Career Launch'],
    jamziaCertification: 'JamZia Bachelor\'s Equivalency Certificate',
    nextGradeId: 'masters1',
    prevGradeId: 'college3',
    description: 'Senior year. Defend your thesis. Graduate with honors.',
    realWorldValue: 'Bachelor\'s equivalency for job applications. Graduate school prep.',
    creditHours: 6,
    tuition: 25,
  },

  // === POSTGRADUATE ===
  {
    id: 'masters1',
    name: 'Masters — Year 1',
    shortName: 'Masters Y1',
    sequence: 19,
    phase: 'postgrad',
    phaseLabel: 'Graduate School',
    testsRequired: 12,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Seminar Gate',
    castleCreature: 'Drakon the Dragon',
    skillsEarned: ['Graduate Research', 'Peer Review', 'Specialization Mastery'],
    jamziaCertification: null,
    nextGradeId: 'masters2',
    prevGradeId: 'college4',
    description: 'Masters begins. Publish or perish. The road demands rigor.',
    realWorldValue: 'Research skills for industry R&D roles. Grant writing prep.',
    creditHours: 9,
    tuition: 50,
  },
  {
    id: 'masters2',
    name: 'Masters — Year 2',
    shortName: 'Masters Y2',
    sequence: 20,
    phase: 'postgrad',
    phaseLabel: 'Graduate School',
    testsRequired: 14,
    passRate: 85,
    phonicsMasteryRequired: true,
    castleGate: 'The Defense Gate',
    castleCreature: 'Viridia the Frog',
    skillsEarned: ['Dissertation Writing', 'Conference Presentation', 'Expert-Level Domain'],
    jamziaCertification: 'JamZia Master\'s Equivalency Certificate',
    nextGradeId: 'phd1',
    prevGradeId: 'masters1',
    description: 'Defend your thesis. Two years of grit ends here.',
    realWorldValue: 'Master\'s equivalency for senior positions. PhD program admission.',
    creditHours: 9,
    tuition: 50,
  },

  // === DOCTORAL (up to 8 years) ===
  {
    id: 'phd1',
    name: 'Doctoral — Year 1',
    shortName: 'PhD Y1',
    sequence: 21,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 10,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Candidacy Gate',
    castleCreature: 'Smash the Shrimp',
    skillsEarned: ['Qualifying Exams', 'Literature Review Mastery', 'Methodology Design'],
    jamziaCertification: null,
    nextGradeId: 'phd2',
    prevGradeId: 'masters2',
    description: 'Doctoral year one. Coursework and qualifying exams.',
    realWorldValue: 'Academic career foundation. Grant eligibility.',
    creditHours: 12,
    tuition: 75,
  },
  {
    id: 'phd2',
    name: 'Doctoral — Year 2',
    shortName: 'PhD Y2',
    sequence: 22,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 10,
    passRate: 80,
    phonicsMasteryRequired: true,
    castleGate: 'The Proposal Gate',
    castleCreature: 'Aurelius the Bull',
    skillsEarned: ['Dissertation Proposal', 'Grant Writing', 'Teaching Practicum'],
    jamziaCertification: null,
    nextGradeId: 'phd3',
    prevGradeId: 'phd1',
    description: 'Dissertation proposal defense. Choose your research path.',
    realWorldValue: 'Grant-funded research skills. Teaching assistantship ready.',
    creditHours: 12,
    tuition: 75,
  },
  {
    id: 'phd3',
    name: 'Doctoral — Year 3',
    shortName: 'PhD Y3',
    sequence: 23,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 12,
    passRate: 85,
    phonicsMasteryRequired: true,
    castleGate: 'The Research Gate',
    castleCreature: 'Arachne the Spider',
    skillsEarned: ['Data Collection', 'Advanced Analytics', 'Publication Pipeline'],
    jamziaCertification: null,
    nextGradeId: 'phd4',
    prevGradeId: 'phd2',
    description: 'Deep research year. Data collection and analysis.',
    realWorldValue: 'Industry research scientist readiness. Publication record.',
    creditHours: 12,
    tuition: 75,
  },
  {
    id: 'phd4',
    name: 'Doctoral — Year 4',
    shortName: 'PhD Y4',
    sequence: 24,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 12,
    passRate: 85,
    phonicsMasteryRequired: true,
    castleGate: 'The Analysis Gate',
    castleCreature: 'Athena the Owl',
    skillsEarned: ['Dissertation Chapters', 'Conference Keynotes', 'Peer Mentoring'],
    jamziaCertification: null,
    nextGradeId: 'phd5',
    prevGradeId: 'phd3',
    description: 'Write your dissertation. Four years of expertise crystallizes.',
    realWorldValue: 'Thought leadership. Consulting and advisory roles.',
    creditHours: 12,
    tuition: 75,
  },
  {
    id: 'phd5',
    name: 'Doctoral — Year 5',
    shortName: 'PhD Y5',
    sequence: 25,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 10,
    passRate: 85,
    phonicsMasteryRequired: true,
    castleGate: 'The Revision Gate',
    castleCreature: 'Sage the Elephant',
    skillsEarned: ['Committee Reviews', 'Revision Mastery', 'Defense Prep'],
    jamziaCertification: null,
    nextGradeId: 'phd6',
    prevGradeId: 'phd4',
    description: 'Committee feedback loops. Revision is research.',
    realWorldValue: 'Editorial and peer-review skills. Academic networking.',
    creditHours: 12,
    tuition: 75,
  },
  {
    id: 'phd6',
    name: 'Doctoral — Year 6',
    shortName: 'PhD Y6',
    sequence: 26,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 10,
    passRate: 90,
    phonicsMasteryRequired: true,
    castleGate: 'The Defense Gate',
    castleCreature: 'Leo the Lion',
    skillsEarned: ['Dissertation Defense', 'Post-Doc Applications', 'Tenure-Track Prep'],
    jamziaCertification: null,
    nextGradeId: 'phd7',
    prevGradeId: 'phd5',
    description: 'Defend your dissertation. Six years culminate in one hour.',
    realWorldValue: 'PhD defense experience. Academic and industry leadership.',
    creditHours: 12,
    tuition: 75,
  },
  {
    id: 'phd7',
    name: 'Doctoral — Year 7',
    shortName: 'PhD Y7',
    sequence: 27,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 8,
    passRate: 90,
    phonicsMasteryRequired: true,
    castleGate: 'The Publication Gate',
    castleCreature: 'Drakon the Dragon',
    skillsEarned: ['Monograph Writing', 'Grant Leadership', 'Department Building'],
    jamziaCertification: null,
    nextGradeId: 'phd8',
    prevGradeId: 'phd6',
    description: 'Extended doctoral work. Book-length contribution to your field.',
    realWorldValue: 'Monograph publication. Department chair readiness.',
    creditHours: 15,
    tuition: 100,
  },
  {
    id: 'phd8',
    name: 'Doctoral — Year 8',
    shortName: 'PhD Y8',
    sequence: 28,
    phase: 'postgrad',
    phaseLabel: 'Doctoral Program',
    testsRequired: 14,
    passRate: 90,
    phonicsMasteryRequired: true,
    castleGate: 'The Infinite Castle Gate',
    castleCreature: 'Leo the Lion',
    skillsEarned: ['Field Leadership', 'Policy Influence', 'Interdisciplinary Mastery'],
    jamziaCertification: 'JamZia Doctoral Equivalency — Highest Honor',
    nextGradeId: null,
    prevGradeId: 'phd7',
    description: 'The pinnacle. Eight years. Infinite Castle conquered. You are a scholar.',
    realWorldValue: 'Highest academic equivalency. Grants, professorships, policy roles.',
    creditHours: 15,
    tuition: 100,
  },
];

/* ── Helpers ── */
export function getGradeById(id: string): GradeLevel | undefined {
  return GRADE_LEVELS.find((g) => g.id === id);
}

export function getCurrentPhase(gradeId: string): string {
  const g = getGradeById(gradeId);
  return g?.phaseLabel || 'Unknown';
}

export function getPhaseColor(phase: string): string {
  const colors: Record<string, string> = {
    early: '#ec4899',
    elementary: '#22c55e',
    middle: '#3b82f6',
    high: '#f59e0b',
    college: '#a855f7',
    postgrad: '#ef4444',
  };
  return colors[phase] || '#6B7280';
}

export const TOTAL_GRADES = GRADE_LEVELS.length; // 29
export const PHASES = ['early', 'elementary', 'middle', 'high', 'college', 'postgrad'] as const;
