/* ═══════════════════════════════════════════════════════════
   PLATFORM REGISTRY — Build Status for All JamZia Platforms
   Built by Collective General Technologies, LLC
   Deadline: July 4, 2026
   ═══════════════════════════════════════════════════════════ */

export type BuildStatus = 'live' | 'beta' | 'alpha' | 'coming_soon' | 'planned';

export interface PlatformInfo {
  name: string;
  route: string;
  category: string;
  status: BuildStatus;
  nowDesc: string;      // What works NOW
  futureDesc: string;   // What Collective General will build
  progress: number;     // 0-100
  relatedLive: string[]; // Related platforms that ARE live
}

export const PLATFORM_REGISTRY: Record<string, PlatformInfo> = {
  // ==== LIVE / BUILT PLATFORMS ====
  '/': {
    name: 'JamZia Home',
    route: '/',
    category: 'Core',
    status: 'live',
    nowDesc: 'SORME search, platform grid, quick links, XRP wallet preview, and 50+ platform directory.',
    futureDesc: 'AI-powered personalized dashboard with predictive content recommendations and real-time activity feeds.',
    progress: 85,
    relatedLive: ['/command', '/profile', '/ask9x'],
  },
  '/command': {
    name: 'Command Center',
    route: '/command',
    category: 'Core',
    status: 'live',
    nowDesc: 'Stats overview, 9 quick-link hubs, XRPL wallet preview, and AI concierge access.',
    futureDesc: 'Real-time analytics dashboard with live platform monitoring, revenue tracking, and automated alerting.',
    progress: 80,
    relatedLive: ['/admin/dashboard', '/profile'],
  },
  '/profile': {
    name: 'User Profile',
    route: '/profile',
    category: 'Core',
    status: 'live',
    nowDesc: 'User settings, avatar, bio, preferences, and connected platforms list.',
    futureDesc: 'Social profile with followers, achievements, portfolio showcase, and cross-platform reputation scores.',
    progress: 75,
    relatedLive: ['/command', '/social'],
  },
  '/ask9x': {
    name: 'Ask 9x Concierge',
    route: '/ask9x',
    category: 'Core',
    status: 'beta',
    nowDesc: 'Template-based concierge with keyword matching, 4-tier depth system, and simulated AI responses.',
    futureDesc: 'Real LLM integration with reasoning chains, 9-node AI mesh routing, conversation memory, and live knowledge updates.',
    progress: 45,
    relatedLive: ['/sorme', '/command'],
  },
  '/sorme': {
    name: 'SORME Search',
    route: '/sorme',
    category: 'Core',
    status: 'beta',
    nowDesc: 'Template-based search with simulated confidence scores and static result sets.',
    futureDesc: 'Real semantic search with BM25 + vector hybrid ranking, search engine backend, and cross-platform unified index.',
    progress: 40,
    relatedLive: ['/ask9x', '/search'],
  },
  '/search': {
    name: 'Universal Search',
    route: '/search',
    category: 'Core',
    status: 'beta',
    nowDesc: 'Basic search interface with category filtering and trending queries.',
    futureDesc: 'AI-powered search with natural language understanding, auto-complete, and personalized result ranking.',
    progress: 50,
    relatedLive: ['/sorme', '/dex'],
  },
  '/pay': {
    name: 'JamPay',
    route: '/pay',
    category: 'Pay',
    status: 'live',
    nowDesc: 'Digital wallet interface, XRPL balance display, and transaction history mockup.',
    futureDesc: 'Full WisdomPay integration with XRPL smart contracts, staking, escrow, and cross-border payments.',
    progress: 65,
    relatedLive: ['/credits', '/wise'],
  },
  '/credits': {
    name: 'JamCredits',
    route: '/credits',
    category: 'Pay',
    status: 'live',
    nowDesc: 'Credit balance display and cross-platform credit tracking.',
    futureDesc: 'Universal credit system with conversion between platforms, rewards, and loyalty point management.',
    progress: 60,
    relatedLive: ['/pay', '/shop'],
  },
  '/wise': {
    name: 'JamWise',
    route: '/wise',
    category: 'Pay',
    status: 'beta',
    nowDesc: 'Financial education articles and basic wealth tracking tools.',
    futureDesc: 'AI-powered financial advisor with portfolio analysis, investment recommendations, and market insights.',
    progress: 55,
    relatedLive: ['/pay', '/grants'],
  },
  '/grants': {
    name: 'JamGrants',
    route: '/grants',
    category: 'Pay',
    status: 'live',
    nowDesc: 'Full grant platform with 8 active grants ($1.03B total), AI match scoring, category filtering, bookmarking, expandable eligibility details, search, and apply workflow.',
    futureDesc: 'AI-matched grant discovery with automated application prep, deadline tracking, and success analytics.',
    progress: 75,
    relatedLive: ['/wise', '/kind'],
  },
  '/shop': {
    name: 'JamShop',
    route: '/shop',
    category: 'Shop',
    status: 'live',
    nowDesc: 'Marketplace interface with product listings, categories, and cart functionality.',
    futureDesc: 'Full e-commerce with AI recommendations, vendor dashboards, inventory sync, and WisdomPay checkout.',
    progress: 70,
    relatedLive: ['/food', '/deals'],
  },
  '/food': {
    name: 'JamFood',
    route: '/food',
    category: 'Shop',
    status: 'live',
    nowDesc: 'Food delivery interface with restaurant listings, menus, and order tracking.',
    futureDesc: 'AI meal planning, nutrition tracking, diet recommendations, and group ordering with split payments.',
    progress: 65,
    relatedLive: ['/shop', '/home'],
  },
  '/auto': {
    name: 'JamAuto',
    route: '/auto',
    category: 'Shop',
    status: 'live',
    nowDesc: 'Auto marketplace with vehicle listings, search filters, and comparison tools.',
    futureDesc: 'Full dealership integration with financing, insurance quotes, test drive booking, and AI price analysis.',
    progress: 60,
    relatedLive: ['/shop', '/techstore'],
  },
  '/learn': {
    name: 'JamLearn',
    route: '/learn',
    category: 'Learn',
    status: 'live',
    nowDesc: 'K-Doctoral academy with 29 grade levels, courses, and progress tracking.',
    futureDesc: 'AI-adaptive curriculum, virtual reality classrooms, and global accreditation partnerships.',
    progress: 80,
    relatedLive: ['/academy', '/courses'],
  },
  '/academy': {
    name: "Mrs. Cotton's Academy",
    route: '/academy',
    category: 'Learn',
    status: 'live',
    nowDesc: 'Phonics Mastery, report cards every 6 weeks, GPA tracking, and gas/brick economy.',
    futureDesc: 'Full K-12 to Doctoral program with AI tutors, virtual labs, and global examination partnerships.',
    progress: 85,
    relatedLive: ['/learn', '/quiz'],
  },
  '/courses': {
    name: 'JamCourses',
    route: '/courses',
    category: 'Learn',
    status: 'live',
    nowDesc: 'Online course catalog with enrollment, progress tracking, and certificates.',
    futureDesc: 'AI-recommended learning paths, peer study groups, and employer-verified skill credentials.',
    progress: 75,
    relatedLive: ['/learn', '/mastery'],
  },
  '/mastery': {
    name: 'JamMastery',
    route: '/mastery',
    category: 'Learn',
    status: 'live',
    nowDesc: 'Skill mastery paths with level progression and achievement badges.',
    futureDesc: 'Gamified skill trees, industry-recognized certifications, and portfolio project validation.',
    progress: 70,
    relatedLive: ['/learn', '/cert'],
  },
  '/quiz': {
    name: 'JamQuiz',
    route: '/quiz',
    category: 'Learn',
    status: 'live',
    nowDesc: 'Knowledge assessment platform with 8 quizzes across blockchain, education, finance, tech, healthcare, media, gaming, and business. Score tracking, difficulty levels, and completion stats.',
    futureDesc: 'AI-generated quizzes, adaptive difficulty, timed competitions, and credential integration.',
    progress: 55,
    relatedLive: [],
  },
  '/boxflix': {
    name: 'JamBoxFlix+',
    route: '/boxflix',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Exclusive content platform with originals, films, series, documentaries, and podcasts.',
    futureDesc: 'Full streaming studio with 4K HDR, offline downloads, watch parties, and creator monetization.',
    progress: 80,
    relatedLive: ['/video', '/streaming'],
  },
  '/video': {
    name: 'JamVideo',
    route: '/video',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Movies and TV shows with categories, ratings, and watchlist.',
    futureDesc: 'Premium VOD with studio partnerships, exclusive premieres, and AI-curated playlists.',
    progress: 70,
    relatedLive: ['/boxflix', '/live'],
  },
  '/streaming': {
    name: 'JamStream',
    route: '/streaming',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Streaming capabilities showcase with 15+ service categories and bundle deals.',
    futureDesc: 'Unified streaming aggregator with single sign-on, cross-service search, and unified billing.',
    progress: 75,
    relatedLive: ['/boxflix', '/ppv'],
  },
  '/live': {
    name: 'JamLive',
    route: '/live',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Live streaming interface with tri-panel layout (live/video/audio) and group chat.',
    futureDesc: 'Multi-cast streaming to all social platforms simultaneously, live commerce, and tipping.',
    progress: 70,
    relatedLive: ['/boxflix', '/groupchat'],
  },
  '/reels': {
    name: 'JamReels',
    route: '/reels',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Full-screen vertical short-form video with like, share, and follow features.',
    futureDesc: 'AI-powered content discovery, creator monetization, and brand partnership marketplace.',
    progress: 75,
    relatedLive: ['/shorts', '/tok'],
  },
  '/shorts': {
    name: 'JamShorts',
    route: '/shorts',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Vertical short-form video with prev/next navigation and creator tools.',
    futureDesc: 'Advanced editing tools, music sync, transitions, and viral trend analytics.',
    progress: 70,
    relatedLive: ['/reels', '/tok'],
  },
  '/ppv': {
    name: 'JamPPV',
    route: '/ppv',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Pay-per-view events with 8 upcoming events across sports, concerts, comedy, and film premieres.',
    futureDesc: 'Global PPV marketplace with live ticketing, replay access, and creator-hosted events.',
    progress: 75,
    relatedLive: ['/boxflix', '/streaming'],
  },
  '/music': {
    name: 'JamMusic',
    route: '/music',
    category: 'Listen',
    status: 'live',
    nowDesc: 'Music streaming with playlists, trending tracks, player bar, and 6 curated playlists.',
    futureDesc: 'Full Hi-Fi streaming with lossless audio, Dolby Atmos, artist profiles, and live concerts.',
    progress: 75,
    relatedLive: ['/audio', '/radio'],
  },
  '/audio': {
    name: 'JamAudio',
    route: '/audio',
    category: 'Listen',
    status: 'beta',
    nowDesc: 'Podcast and audiobook directory with basic playback.',
    futureDesc: 'Full podcast studio with recording, editing, distribution, and monetization tools.',
    progress: 60,
    relatedLive: ['/music', '/radio'],
  },
  '/radio': {
    name: 'JamRadio',
    route: '/radio',
    category: 'Listen',
    status: 'live',
    nowDesc: 'Live radio streaming with 6 stations, 271.5K total listeners, schedule, trending, now playing with full controls, and station creation tools.',
    futureDesc: 'User-generated stations, podcast integration, live call-in, and advertising marketplace.',
    progress: 55,
    relatedLive: [],
  },
  '/groupchat': {
    name: 'JamGroupChat',
    route: '/groupchat',
    category: 'Connect',
    status: 'live',
    nowDesc: '10 chat rooms across categories with real-time messaging, pinned channels, and unread badges.',
    futureDesc: 'End-to-end encrypted rooms, voice channels, screen sharing, and community governance tools.',
    progress: 80,
    relatedLive: ['/social', '/forum'],
  },
  '/social': {
    name: 'JamSocial',
    route: '/social',
    category: 'Connect',
    status: 'beta',
    nowDesc: 'Social network profile, feed, and basic following system.',
    futureDesc: 'Full social platform with stories, reels, marketplace integration, and creator economy.',
    progress: 60,
    relatedLive: ['/groupchat', '/network'],
  },
  '/battle': {
    name: 'JamBattle',
    route: '/battle',
    category: 'Play',
    status: 'live',
    nowDesc: 'Cotton Brick Road game with AR creature collection, levels, and leaderboard.',
    futureDesc: 'Full MMO with guilds, raids, tournaments, and cross-platform progression.',
    progress: 75,
    relatedLive: ['/games', '/arena'],
  },
  '/games': {
    name: 'JamGames',
    route: '/games',
    category: 'Play',
    status: 'beta',
    nowDesc: 'Game library with catalog and basic arcade classics.',
    futureDesc: 'AAA game streaming, cloud saves, achievements, and esports tournament integration.',
    progress: 55,
    relatedLive: ['/battle', '/ar'],
  },
  '/ar': {
    name: 'JamAR',
    route: '/ar',
    category: 'Play',
    status: 'live',
    nowDesc: 'AR creature viewer with 13 transparent PNG creatures and scene backgrounds.',
    futureDesc: 'Full AR engine with world mapping, multiplayer AR, and location-based quests.',
    progress: 70,
    relatedLive: ['/battle', '/quest'],
  },
  '/coins': {
    name: 'JamCoins',
    route: '/coins',
    category: 'Play',
    status: 'live',
    nowDesc: 'AR crypto coin collection game with 8 coin types, wallet, and leaderboard.',
    futureDesc: 'Full Pokemon Go-style AR with trading, NFT minting, and real-world merchant redemption.',
    progress: 70,
    relatedLive: ['/battle', '/pay'],
  },
  '/architecture': {
    name: 'Architecture',
    route: '/architecture',
    category: 'System',
    status: 'live',
    nowDesc: '11-layer architecture visualization with build status and node descriptions.',
    futureDesc: 'Interactive 3D architecture explorer with live metrics and system health monitoring.',
    progress: 85,
    relatedLive: ['/layers', '/command'],
  },
  '/layers': {
    name: '11-Layers',
    route: '/layers',
    category: 'System',
    status: 'live',
    nowDesc: 'Detailed layer cards with 4 tabs (What It Is, What It Does, How It Helps, Coming Soon).',
    futureDesc: 'Real-time layer monitoring with health dashboards, deployment logs, and auto-scaling triggers.',
    progress: 90,
    relatedLive: ['/architecture', '/command'],
  },
  '/app': {
    name: 'Desktop App',
    route: '/app',
    category: 'System',
    status: 'live',
    nowDesc: 'Desktop download page with system requirements and installer links.',
    futureDesc: 'Native desktop app with offline mode, system tray, and native notifications.',
    progress: 60,
    relatedLive: ['/ios', '/android'],
  },
  '/ios': {
    name: 'iOS App',
    route: '/ios',
    category: 'System',
    status: 'live',
    nowDesc: 'iOS download page with App Store link and feature highlights.',
    futureDesc: 'Native iOS app with widgets, Siri shortcuts, and Apple Watch companion.',
    progress: 60,
    relatedLive: ['/app', '/android'],
  },
  '/android': {
    name: 'Android App',
    route: '/android',
    category: 'System',
    status: 'live',
    nowDesc: 'Android download page with Google Play link and feature highlights.',
    futureDesc: 'Native Android app with widgets, Wear OS support, and deep system integration.',
    progress: 60,
    relatedLive: ['/app', '/ios'],
  },
  '/admin/dashboard': {
    name: 'Admin Dashboard',
    route: '/admin/dashboard',
    category: 'System',
    status: 'live',
    nowDesc: 'Admin panel with user management, content moderation, and system overview.',
    futureDesc: 'Full admin suite with analytics, role management, white-label controls, and audit trails.',
    progress: 70,
    relatedLive: ['/command', '/audit'],
  },
  '/ai-nodes': {
    name: 'AI Nodes',
    route: '/ai-nodes',
    category: 'System',
    status: 'live',
    nowDesc: '9-node AI architecture visualization with PRIME-Σ to AEGIS-09 descriptions.',
    futureDesc: 'Live node monitoring with inference metrics, load balancing, and auto-scaling.',
    progress: 75,
    relatedLive: ['/architecture', '/command'],
  },
  '/ledger': {
    name: 'Operations Ledger',
    route: '/ledger',
    category: 'System',
    status: 'live',
    nowDesc: 'Immutable artifact registry with 6 artifact families and mock ledger.',
    futureDesc: 'Live blockchain-backed ledger with smart contract verification and audit trails.',
    progress: 65,
    relatedLive: ['/architecture', '/admin/dashboard'],
  },
  '/wl-brands': {
    name: 'White Label Hub',
    route: '/wl-brands',
    category: 'System',
    status: 'live',
    nowDesc: 'DIY white label program with 14 brands, brand registry, and hub pages.',
    futureDesc: 'Self-service white label creation with brand builder, theme editor, and deployment pipeline.',
    progress: 80,
    relatedLive: ['/NoFear', '/BlackDiamond'],
  },

  // ==== NOFEAR / WHITE LABEL ====
  '/NoFear': {
    name: 'NoFear™',
    route: '/NoFear',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Fearless Revolution Foundation community app with 50+ platform access.',
    futureDesc: 'Dedicated NoFear instance with custom branding, community governance, and mental health focus.',
    progress: 85,
    relatedLive: ['/wl-brands', '/groupchat'],
  },
  '/BlackDiamond': {
    name: 'BlackDiamond™',
    route: '/BlackDiamond',
    category: 'White Label',
    status: 'live',
    nowDesc: 'BlackDiamond Media Group hub with media, advertising, and publishing platforms.',
    futureDesc: 'Full media ecosystem with studios, records, and publishing under unified brand.',
    progress: 80,
    relatedLive: ['/wl-brands', '/boxflix'],
  },
  '/BlackDiamondStudios': {
    name: 'BlackDiamond Studios',
    route: '/BlackDiamondStudios',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Film and TV production arm with original content showcase.',
    futureDesc: 'Full-service studio with production pipeline, distribution, and talent management.',
    progress: 75,
    relatedLive: ['/boxflix', '/wl-brands'],
  },
  '/BlackDiamondRecords': {
    name: 'BlackDiamond Records',
    route: '/BlackDiamondRecords',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Music label and audio production division with artist showcase.',
    futureDesc: 'Full record label with studio booking, distribution, and royalty management.',
    progress: 70,
    relatedLive: ['/music', '/wl-brands'],
  },
  '/BlackDiamondPublishing': {
    name: 'BlackDiamond Publishing',
    route: '/BlackDiamondPublishing',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Book publishing and educational materials division.',
    futureDesc: 'Global publishing house with print-on-demand, ebook, and audiobook distribution.',
    progress: 70,
    relatedLive: ['/library', '/wl-brands'],
  },
  '/MrsCotton': {
    name: "Mrs. Cotton's Academy",
    route: '/MrsCotton',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Dedicated education brand hub with K-Doctoral programs and Phonics Mastery.',
    futureDesc: 'Global online school with accreditation, virtual classrooms, and parent portals.',
    progress: 85,
    relatedLive: ['/academy', '/wl-brands'],
  },
  '/Ad9xPharma': {
    name: 'Ad9x Pharmaceuticals',
    route: '/Ad9xPharma',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Healthcare innovation division with digital health platforms.',
    futureDesc: 'Telemedicine platform, pharmaceutical research coordination, and patient care management.',
    progress: 60,
    relatedLive: ['/health', '/wl-brands'],
  },
  '/WisdomPay': {
    name: 'WisdomPay',
    route: '/WisdomPay',
    category: 'White Label',
    status: 'live',
    nowDesc: 'XRPL payment platform with wallet, staking, and cross-border transfers.',
    futureDesc: 'Full DeFi suite with lending, borrowing, yield farming, and institutional custody.',
    progress: 65,
    relatedLive: ['/pay', '/wl-brands'],
  },
  '/RockNext': {
    name: 'RockNext',
    route: '/RockNext',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Music creation and distribution platform for independent artists.',
    futureDesc: 'Full music ecosystem with creation tools, distribution, and live performance booking.',
    progress: 65,
    relatedLive: ['/music', '/wl-brands'],
  },
  '/SkyLockr': {
    name: 'SkyLockr',
    route: '/SkyLockr',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Secure storage and file management platform.',
    futureDesc: 'Enterprise-grade vault with encryption, sharing, and blockchain verification.',
    progress: 65,
    relatedLive: ['/vault', '/wl-brands'],
  },
  '/Conduit': {
    name: 'Conduit Capital AI',
    route: '/Conduit',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Institutional DeFi and investment advisory platform.',
    futureDesc: 'Full wealth management with AI portfolio optimization and institutional reporting.',
    progress: 65,
    relatedLive: ['/wise', '/wl-brands'],
  },
  '/RiverShyre': {
    name: 'RiverShyre',
    route: '/RiverShyre',
    category: 'White Label',
    status: 'live',
    nowDesc: 'AR gaming and interactive entertainment platform.',
    futureDesc: 'AAA AR game studio with world-building, multiplayer, and NFT asset marketplace.',
    progress: 65,
    relatedLive: ['/ar', '/wl-brands'],
  },
  '/Collective': {
    name: 'Collective General',
    route: '/Collective',
    category: 'White Label',
    status: 'live',
    nowDesc: 'Infrastructure and technology consulting division.',
    futureDesc: 'Full-stack DevOps platform with monitoring, CI/CD, and cloud orchestration.',
    progress: 65,
    relatedLive: ['/cloud', '/wl-brands'],
  },

  // ==== JAMDAVE™ ENGINE — DAW-Integrated Digital Audio/Video Infrastructure · Pro Tools · Studio One · Logic ====
  '/upload': {
    name: 'UploadStudio',
    route: '/upload',
    category: 'Build',
    status: 'live',
    nowDesc: 'Drag-drop multipart upload with file type detection, Pro Tools/Studio One/Logic project import, visibility/category/tag settings, and JamDAVE™ upload pipeline visualization. Direct-to-JamDAVE™ via presigned URLs.',
    futureDesc: 'Real multipart upload with progress tracking, automatic ABR transcoding queue, and thumbnail generation.',
    progress: 75,
    relatedLive: ['/library', '/golive'],
  },
  '/golive': {
    name: 'GoLive',
    route: '/golive',
    category: 'Build',
    status: 'live',
    nowDesc: 'Live streaming dashboard with stream creation, RTMP key management, HLS/WebRTC playback URLs, viewer count simulation, start/end stream controls, and encoder configuration guide.',
    futureDesc: 'Real WebRTC → RTMP relay, live chat integration, donation overlays, and recording auto-archive to JamDAVE™ storage.',
    progress: 70,
    relatedLive: ['/upload', '/tiers'],
  },
  '/tiers': {
    name: 'MediaTiers',
    route: '/tiers',
    category: 'Build',
    status: 'live',
    nowDesc: '6-tier pricing table (Entry/Pro/Master/Prime/Network/Custom) with wholesale vs retail transparency, cost calculator with Ad9x 20% fee breakdown, and ABR resolution explainer.',
    futureDesc: 'Real-time usage tracking, automated billing, tier upgrade/downgrade with proration, and usage alerts.',
    progress: 80,
    relatedLive: ['/upload', '/library'],
  },
  '/medialibrary': {
    name: 'MediaLibrary',
    route: '/medialibrary',
    category: 'Build',
    status: 'live',
    nowDesc: 'decentralized storage asset browser with grid/list views, type/visibility filters, search, asset detail modal with playback, visibility editor, and delete confirmation.',
    futureDesc: 'Full playback with HLS.js integration, DAW timeline sync, Pro Tools/Studio One/Logic project export, folder organization, batch operations, and sharing links.',
    progress: 70,
    relatedLive: ['/upload', '/golive'],
  },
  '/dave': {
    name: 'JamDAVE Engine',
    route: '/dave',
    category: 'Build',
    status: 'live',
    nowDesc: 'Digital Audio/Video Engine with 8 capabilities: Create, Edit, Mix, Master, Playlist, Store, Monetize, Distribute. Pro Tools, Studio One, Logic integration. WisdomPay, XRPL, Bitcoin Lightning, Storj, LivePeer, NFT minting from production. White label ready.',
    futureDesc: 'Full DAW-in-the-browser with real-time collaboration, AI-assisted mastering, automated distribution to all major platforms, and live performance mode.',
    progress: 80,
    relatedLive: ['/upload', '/golive', '/tiers', '/library'],
  },
  '/creators': {
    name: 'JamDAVE Creators',
    route: '/creators',
    category: 'Build',
    status: 'live',
    nowDesc: 'Alias route to JamDAVE Engine. Full creator suite for audio/video production, distribution, and monetization.',
    futureDesc: 'Same as JamDAVE Engine — dedicated creator portal with audience analytics and revenue dashboard.',
    progress: 80,
    relatedLive: ['/dave', '/upload'],
  },
  '/jamex': {
    name: 'JamEx Explainer Videos',
    route: '/jamex',
    category: 'Learn',
    status: 'live',
    nowDesc: '100% AI-generated explainer videos with animal/bug guides teaching JamZia at a 5th-grade level. One video per major platform. Battle quizzes unlock the next lesson.',
    futureDesc: 'Full AI video pipeline generating custom explainers for every new feature. Multi-language support.',
    progress: 75,
    relatedLive: ['/cottonbrickroad', '/castle'],
  },
  '/cottonbrickroad': {
    name: 'Cotton Brick Road',
    route: '/cottonbrickroad',
    category: 'Learn',
    status: 'live',
    nowDesc: 'Gamified 11-stage education system. Walk the road, earn badges, collect XP, and reach The Castle. Each stage teaches one JamZia platform with battle quizzes.',
    futureDesc: 'Full RPG progression with avatar customization, multiplayer challenges, and real rewards tied to platform usage.',
    progress: 80,
    relatedLive: ['/jamex', '/castle'],
  },
  '/castle': {
    name: 'The Castle',
    route: '/castle',
    category: 'Build',
    status: 'live',
    nowDesc: 'Creative submission portal for songs, music videos, episodes, documentaries, and feature films. One upload distributes to all JamZia platforms and worldwide channels.',
    futureDesc: 'Automated review pipeline, AI quality scoring, and direct distribution deals with external platforms.',
    progress: 70,
    relatedLive: ['/dave', '/cottonbrickroad'],
  },
  '/jamzastream': {
    name: 'JamZa Stream',
    route: '/jamzastream',
    category: 'Watch',
    status: 'live',
    nowDesc: 'Total decentralized streaming solution — LiveStream, VOD, PPV. Encode and edit on the fly. Asset storage and management. Monetization with SVOD, AVOD, TVOD.',
    futureDesc: 'Full AI-powered live encoding, automated scene detection, real-time translation, and global edge expansion.',
    progress: 75,
    relatedLive: ['/golive', '/tiers', '/dave'],
  },

  // ==== COMING SOON / NOT YET BUILT ====
  '/sound': {
    name: 'JamSound',
    route: '/sound',
    category: 'Sound',
    status: 'live',
    nowDesc: 'Sound effects and audio asset library.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/beats': {
    name: 'JamBeats',
    route: '/beats',
    category: 'Beats',
    status: 'live',
    nowDesc: 'Beat marketplace for producers and artists.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/studio': {
    name: 'JamStudio',
    route: '/studio',
    category: 'Listen',
    status: 'live',
    nowDesc: 'Full cloud recording studio with 7 tracks, transport controls, timeline with clips, volume/pan per track, mute/solo, master effects panel, and export to JamMusic.',
    futureDesc: 'Virtual instruments, real-time collaboration, VST plugin support, and BlackDiamond Records direct export.',
    progress: 55,
    relatedLive: [],
  },
  '/live-audio': {
    name: 'JamLiveAudio',
    route: '/live-audio',
    category: 'Live Audio',
    status: 'live',
    nowDesc: 'Live audio streaming and broadcasting.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/loop': {
    name: 'JamLoop',
    route: '/loop',
    category: 'Loop',
    status: 'live',
    nowDesc: 'Audio loops and sample marketplace.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/pod': {
    name: 'JamPod',
    route: '/pod',
    category: 'Pod',
    status: 'live',
    nowDesc: 'Podcast hosting and distribution platform.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/films': {
    name: 'JamFilms',
    route: '/films',
    category: 'Films',
    status: 'live',
    nowDesc: 'Documentary and film library with original content.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/premiere': {
    name: 'JamPremiere',
    route: '/premiere',
    category: 'Premiere',
    status: 'live',
    nowDesc: 'Premiere nights and exclusive screenings.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/arena': {
    name: 'JamArena',
    route: '/arena',
    category: 'Play',
    status: 'live',
    nowDesc: 'Tournament arena with 6 live events (Cotton Cup, SkyIvy Concert, AR Showdown, Word Weave Masters, NoFear Invitational, BlackDiamond Chess Masters), 510K JAM prize pool, registration system, global leaderboard with 8 ranked players, and host tools.',
    futureDesc: 'Live bracket management, streaming integration, spectator modes, and skill-based tournament formats.',
    progress: 60,
    relatedLive: ['/battle', '/games'],
  },
  '/jamu': {
    name: 'JamU',
    route: '/jamu',
    category: 'Learn',
    status: 'live',
    nowDesc: 'Complete education platform with 159+ free Saylor Academy courses (7 categories) + 6 premium Ad9x courses. Free certificates, Learning to Earn pathways, tiered pricing. Tagline: "You get what you pay for. After the free."',
    futureDesc: 'Full Saylor course catalog integration, 1-on-1 mentorship marketplace, XRPL-verified credentials, BlackDiamond job placement, and Learning to Earn career pipelines.',
    progress: 60,
    relatedLive: ['/academy', '/grants'],
  },
  '/rpg': {
    name: 'JamRPG',
    route: '/rpg',
    category: 'Rpg',
    status: 'live',
    nowDesc: 'Role-playing game platform with character creation.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/puzzle': {
    name: 'JamPuzzle',
    route: '/puzzle',
    category: 'Puzzle',
    status: 'live',
    nowDesc: 'Brain games and puzzle marketplace.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/quest': {
    name: 'JamQuest',
    route: '/quest',
    category: 'Quest',
    status: 'live',
    nowDesc: 'AR quests and reward-based challenges.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/dex': {
    name: 'JamDEX',
    route: '/dex',
    category: 'Pay',
    status: 'live',
    nowDesc: 'Full DEX interface with 5 tokens (XRP, SKYI, SKYL, JAM, WISD), real-time price chart, order book with depth visualization, recent trades feed, 5 liquidity pools with TVL/APR, swap panel with slippage protection, and wallet preview.',
    futureDesc: 'AMM liquidity pools, limit orders, cross-chain bridges, and sub-second XRPL settlement.',
    progress: 65,
    relatedLive: ['/pay', '/swap'],
  },
  '/escrow': {
    name: 'JamEscrow',
    route: '/escrow',
    category: 'Escrow',
    status: 'live',
    nowDesc: 'Smart contract escrow service for secure transactions.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/swap': {
    name: 'JamSwap',
    route: '/swap',
    category: 'Swap',
    status: 'live',
    nowDesc: 'Token swap engine for cross-chain exchanges.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/vault': {
    name: 'JamVault',
    route: '/vault',
    category: 'Pay',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Secure asset vault with cold storage simulation, multi-sig wallets, and insurance-backed custody. Time-locked releases and beneficiary designation for estate planning.',
    progress: 15,
    relatedLive: ['/pay', '/escrow'],
  },
  '/staking': {
    name: 'JamStaking',
    route: '/staking',
    category: 'Pay',
    status: 'live',
    nowDesc: 'Staking dashboard with 5 pools (XRP Core 8.5%, SkyIvy Growth 14.2%, SkyLockr Secure 10.8%, JamCoin Launch 28.5%, Wisdom Governance 12.0%), stake/unstake panel with APY calculator, lock period display, and reward estimates.',
    futureDesc: 'Auto-restaking, validator selection, compound interest visualization, and governance voting.',
    progress: 60,
    relatedLive: ['/pay', '/dex'],
  },
  '/deals': {
    name: 'JamDeals',
    route: '/deals',
    category: 'Deals',
    status: 'live',
    nowDesc: 'Daily deals and offer aggregator.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/fashion': {
    name: 'JamFashion',
    route: '/fashion',
    category: 'Fashion',
    status: 'live',
    nowDesc: 'Fashion and style marketplace.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/techstore': {
    name: 'JamTechStore',
    route: '/techstore',
    category: 'Techstore',
    status: 'live',
    nowDesc: 'Technology and gadget store.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/home': {
    name: 'JamHome',
    route: '/home',
    category: 'Shop',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Home goods marketplace with room visualization, AR furniture placement, and interior design AI. Contractor marketplace for installation services.',
    progress: 10,
    relatedLive: ['/shop', '/fashion'],
  },
  '/tickets': {
    name: 'JamTickets',
    route: '/tickets',
    category: 'Tickets',
    status: 'live',
    nowDesc: 'Event ticketing and venue management.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/goods': {
    name: 'JamGoods',
    route: '/goods',
    category: 'Goods',
    status: 'live',
    nowDesc: 'Physical goods marketplace.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/cert': {
    name: 'JamCert',
    route: '/cert',
    category: 'Cert',
    status: 'live',
    nowDesc: 'Certifications and credential management.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/library': {
    name: 'JamLibrary',
    route: '/library',
    category: 'Library',
    status: 'live',
    nowDesc: 'Digital library with categorized resources.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/labs': {
    name: 'JamLabs',
    route: '/labs',
    category: 'Labs',
    status: 'live',
    nowDesc: 'Virtual labs and experiment simulations.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/tutor': {
    name: 'JamTutor',
    route: '/tutor',
    category: 'Tutor',
    status: 'live',
    nowDesc: 'One-on-one tutoring marketplace.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/dating': {
    name: 'JamDating',
    route: '/dating',
    category: 'Dating',
    status: 'live',
    nowDesc: 'Social matching and connection platform.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/forum': {
    name: 'JamForum',
    route: '/forum',
    category: 'Connect',
    status: 'live',
    nowDesc: 'Full community forum with 8 topics (announcements, updates, questions, opportunities), 6 community hubs, upvote/downvote system, trending tags, hot/new/top sorting, pinned posts, and 148K member stats.',
    futureDesc: 'Threaded discussions, reputation system, expert badges, and JamGroupChat real-time integration.',
    progress: 55,
    relatedLive: ['/groupchat', '/social'],
  },
  '/network': {
    name: 'JamNetwork',
    route: '/network',
    category: 'Network',
    status: 'live',
    nowDesc: 'Professional networking with skill endorsements.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/family': {
    name: 'JamFamily',
    route: '/family',
    category: 'Family',
    status: 'live',
    nowDesc: 'Family sharing and coordination hub.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/mail': {
    name: 'JamMail',
    route: '/mail',
    category: 'Mail',
    status: 'live',
    nowDesc: 'Secure messaging platform with encryption.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/events': {
    name: 'JamEvents',
    route: '/events',
    category: 'Connect',
    status: 'live',
    nowDesc: 'Event discovery platform with 8 events (Launch Party, Concert Series, Cotton Cup, Workshops, Summit, Film Premiere, Trading Competition), category filtering, RSVP system, featured event cards, and host tools.',
    futureDesc: 'Ticketing with WisdomPay, live streaming, venue marketplace, and post-event galleries.',
    progress: 55,
    relatedLive: ['/ppv', '/tickets'],
  },
  '/tok': {
    name: 'JamTok',
    route: '/tok',
    category: 'Connect',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Short video social platform with duets, stitches, and trending sounds. Creator fund, brand deals marketplace, and live shopping integration. Algorithm-powered discovery feed.',
    progress: 15,
    relatedLive: ['/reels', '/shorts'],
  },
  '/code': {
    name: 'JamCode',
    route: '/code',
    category: 'Code',
    status: 'live',
    nowDesc: 'Cloud IDE with code editor, syntax highlighting, and deployment pipeline.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/cloud': {
    name: 'JamCloud',
    route: '/cloud',
    category: 'Build',
    status: 'live',
    nowDesc: 'Full cloud hosting dashboard with 5 live instances, create/stop/delete controls, CPU/RAM monitoring, region selection (4 zones), instance type picker, and provisioning animations.',
    futureDesc: 'Auto-scaling, container orchestration, Kubernetes integration, and edge deployment across 50+ global regions.',
    progress: 65,
    relatedLive: ['/deploy', '/monitor'],
  },
  '/api': {
    name: 'JamAPI',
    route: '/api',
    category: 'Build',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'API gateway with rate limiting, request transformation, and unified billing. GraphQL and REST endpoints for all 50+ platforms. Developer portal with sandbox testing.',
    progress: 15,
    relatedLive: ['/devdocs', '/code'],
  },
  '/devdocs': {
    name: 'JamDevDocs',
    route: '/devdocs',
    category: 'Build',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Developer documentation with interactive code examples, API explorer, and SDK downloads. Auto-generated from source code. Community contributions and versioned docs.',
    progress: 10,
    relatedLive: ['/api', '/code'],
  },
  '/deploy': {
    name: 'JamDeploy',
    route: '/deploy',
    category: 'Build',
    status: 'live',
    nowDesc: 'CI/CD pipeline dashboard with 5 pipelines (JamZia Main, JamPay API, JamDEX Engine, NoFear WL, BlackDiamond Media), visual stage flow (Lint → Build → Security → Deploy), expandable logs per stage, environment cards, and trigger controls.',
    futureDesc: 'Blue-green deployments, canary releases, A/B testing, and auto-rollback on failure.',
    progress: 60,
    relatedLive: ['/cloud', '/ci'],
  },
  '/ci': {
    name: 'JamCI',
    route: '/ci',
    category: 'Ci',
    status: 'live',
    nowDesc: 'CI/CD automation and build pipelines.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/monitor': {
    name: 'JamMonitor',
    route: '/monitor',
    category: 'Build',
    status: 'live',
    nowDesc: 'Real-time monitoring dashboard with 10 service status cards, CPU/memory/network sparklines, severity-filtered alerts feed with acknowledge capability, and global uptime tracking.',
    futureDesc: 'Prometheus/Grafana integration, SLO tracking, PagerDuty webhooks, and custom metric pipelines.',
    progress: 60,
    relatedLive: ['/cloud', '/command'],
  },
  '/bot': {
    name: 'JamBot',
    route: '/bot',
    category: 'Build',
    status: 'live',
    nowDesc: 'AI-powered bot creation and automation platform.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: ['/auto', '/command'],
  },
  '/form': {
    name: 'JamForm',
    route: '/form',
    category: 'Form',
    status: 'live',
    nowDesc: 'Form builder and survey platform.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/law': {
    name: 'JamLaw',
    route: '/law',
    category: 'Govern',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Legal resources with document templates, e-signature, and attorney marketplace. Contract review AI, compliance checkers, and dispute resolution tools. State-by-state law guides.',
    progress: 15,
    relatedLive: ['/docs-legal', '/compliance'],
  },
  '/fed': {
    name: 'JamFed',
    route: '/fed',
    category: 'Govern',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Federal program navigator with benefit eligibility, application assistance, and status tracking. Integration with USA.gov APIs. Multi-language support for immigrant communities.',
    progress: 10,
    relatedLive: ['/state', '/local'],
  },
  '/state': {
    name: 'JamState',
    route: '/state',
    category: 'Govern',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'State services portal with DMV, tax, licensing, and unemployment tools. Document upload, appointment scheduling, and status tracking. All 50 states supported.',
    progress: 10,
    relatedLive: ['/fed', '/local'],
  },
  '/local': {
    name: 'JamLocal',
    route: '/local',
    category: 'Local',
    status: 'live',
    nowDesc: 'Local government services and information.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/docs-legal': {
    name: 'JamDocsLegal',
    route: '/docs-legal',
    category: 'Docs Legal',
    status: 'live',
    nowDesc: 'Legal document templates and resources.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/tax': {
    name: 'JamTax',
    route: '/tax',
    category: 'Govern',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Tax compliance with filing assistance, deduction finder, and audit protection. Integration with IRS e-file. Business and personal tax support. Multi-year comparison and planning tools.',
    progress: 10,
    relatedLive: ['/law', '/wise'],
  },
  '/compliance': {
    name: 'JamCompliance',
    route: '/compliance',
    category: 'Compliance',
    status: 'live',
    nowDesc: 'Regulatory compliance tracking.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/vote': {
    name: 'JamVote',
    route: '/vote',
    category: 'Vote',
    status: 'live',
    nowDesc: 'Voting and polling platform with blockchain verification.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/policy': {
    name: 'JamPolicy',
    route: '/policy',
    category: 'Policy',
    status: 'live',
    nowDesc: 'Policy tracking and government monitoring.',
    futureDesc: 'Expanded feature set with AI integration and XRPL verification.',
    progress: 50,
    relatedLive: [],
  },
  '/health': {
    name: 'JamHealth',
    route: '/health',
    category: 'Health',
    status: 'beta',
    nowDesc: 'Basic health information and resource directory.',
    futureDesc: 'Telemedicine platform with video consultations, prescription management, and health records. Integration with Ad9x Pharmaceuticals for research coordination.',
    progress: 40,
    relatedLive: ['/psych', '/therapy'],
  },
  '/psych': {
    name: 'JamPsych',
    route: '/psych',
    category: 'Health',
    status: 'beta',
    nowDesc: 'Mental health resources and therapist directory.',
    futureDesc: 'Full teletherapy platform with licensed providers, session scheduling, and progress tracking. HIPAA-compliant with insurance integration.',
    progress: 45,
    relatedLive: ['/therapy', '/health'],
  },
  '/therapy': {
    name: 'JamTherapy',
    route: '/therapy',
    category: 'Health',
    status: 'beta',
    nowDesc: 'Therapy session booking and wellness tracking.',
    futureDesc: 'Complete therapy suite with video sessions, messaging, homework assignments, and outcome measurement. Group therapy and specialized programs.',
    progress: 45,
    relatedLive: ['/psych', '/health'],
  },
  '/kind': {
    name: 'JamKind',
    route: '/kind',
    category: 'Community',
    status: 'beta',
    nowDesc: 'Kindness initiative with volunteer matching and community service tracking.',
    futureDesc: 'Full volunteer ecosystem with hours tracking, skill-based matching, and nonprofit partnerships. Gamified with JamCoins rewards.',
    progress: 50,
    relatedLive: ['/grants', '/social'],
  },
  '/docs': {
    name: 'JamDocs',
    route: '/docs',
    category: 'System',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Comprehensive documentation hub with API docs, guides, tutorials, and changelogs. Searchable, versioned, and community-editable.',
    progress: 10,
    relatedLive: ['/devdocs', '/api'],
  },
  '/audit': {
    name: 'Audit Logs',
    route: '/audit',
    category: 'System',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Immutable audit trail with blockchain verification, real-time alerts, and compliance reporting. Tamper-proof logs for all platform operations.',
    progress: 15,
    relatedLive: ['/admin/dashboard', '/compliance'],
  },
  '/status': {
    name: 'System Status',
    route: '/status',
    category: 'System',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Real-time status page with uptime monitoring, incident history, and subscription alerts. Public API for third-party status dashboards.',
    progress: 15,
    relatedLive: ['/monitor', '/command'],
  },
  '/documentation': {
    name: 'Documentation',
    route: '/documentation',
    category: 'System',
    status: 'coming_soon',
    nowDesc: 'Placeholder route — no dedicated page exists yet.',
    futureDesc: 'Central documentation repository with technical specs, architecture diagrams, and deployment guides. Auto-synced with code changes.',
    progress: 10,
    relatedLive: ['/docs', '/devdocs'],
  },
};

/* Helper to get platform info by route */
export function getPlatformInfo(route: string): PlatformInfo | undefined {
  // Exact match
  if (PLATFORM_REGISTRY[route]) return PLATFORM_REGISTRY[route];
  
  // Try without trailing slash
  const clean = route.replace(/\/$/, '');
  if (PLATFORM_REGISTRY[clean]) return PLATFORM_REGISTRY[clean];
  
  // Try adding leading slash
  if (!route.startsWith('/')) {
    return PLATFORM_REGISTRY['/' + route];
  }
  
  return undefined;
}

/* Helper to check if route is built */
export function isRouteBuilt(route: string): boolean {
  const info = getPlatformInfo(route);
  if (!info) return false;
  return info.status === 'live' || info.status === 'beta';
}

/* Get all coming soon platforms */
export function getComingSoonPlatforms(): PlatformInfo[] {
  return Object.values(PLATFORM_REGISTRY).filter(
    (p) => p.status === 'coming_soon' || p.status === 'planned'
  );
}

/* Get all live platforms */
export function getLivePlatforms(): PlatformInfo[] {
  return Object.values(PLATFORM_REGISTRY).filter(
    (p) => p.status === 'live' || p.status === 'beta'
  );
}
