// ═══════════════════════════════════════════════════════════
// JamZia DIY White-Label Program — Brand Registry
// (c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company
// ═══════════════════════════════════════════════════════════

export type BrandId = 'NoFear' | 'RockNext' | 'SkyLockr' | 'BlackDiamond' | 'BlackDiamondStudios' | 'BlackDiamondRecords' | 'BlackDiamondPublishing' | 'Conduit' | 'RiverShyre' | 'Collective' | 'WisdomPay' | 'Ad9x' | 'Ad9xPharma' | 'MrsCotton';

export interface WLBrand {
  id: BrandId;
  name: string;
  fullLegalName: string;
  org: string;
  wlId: string;
  tagline: string;
  mission: string;
  poweredBy: string;
  copyright: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  bgGradient: string;
  icon: string;
  heroTitle: string;
  heroSubtitle: string;
  heroDescription: string;
  ctaPrimary: string;
  ctaPrimaryLink: string;
  ctaSecondary: string;
  ctaSecondaryLink: string;
  stats: { label: string; value: string }[];
  platformFilter: string[]; // which platform categories to show
  showCrisisBanner: boolean;
  showCottonBrickRoad: boolean;
  showJamRep: boolean;
}

export const WL_BRANDS: Record<BrandId, WLBrand> = {
  NoFear: {
    id: 'NoFear',
    name: 'NoFear',
    fullLegalName: 'NoFear™',
    org: 'Fearless Revolution Foundation',
    wlId: 'WL-001',
    tagline: 'A Message of Hope for the World',
    mission: 'NoFear™ is the community app of Fearless Revolution Foundation, providing safe, supportive access to mental health resources, educational pathways, professional services, and community connection.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#4A90A4',
    secondaryColor: '#D4A574',
    accentColor: '#f59e0b',
    bgGradient: 'linear-gradient(180deg, #1A1A2E 0%, #16213E 50%, #0F3460 100%)',
    icon: '✦',
    heroTitle: 'NoFear™',
    heroSubtitle: 'the community app of Fearless Revolution Foundation',
    heroDescription: 'A safe space for healing, learning, and growth. 50+ platforms, one membership, zero fear.',
    ctaPrimary: 'Get Help Now',
    ctaPrimaryLink: '/nofear/therapy',
    ctaSecondary: 'Explore NoFearLearn',
    ctaSecondaryLink: '/nofear/learn',
    stats: [
      { label: 'Platforms', value: '50+' },
      { label: 'Resources', value: '100M+' },
      { label: 'Reach', value: 'Global' },
    ],
    platformFilter: ['Healing', 'Media', 'Finance', 'World', 'Intel', 'Gov', 'Health'],
    showCrisisBanner: true,
    showCottonBrickRoad: true,
    showJamRep: true,
  },

  RockNext: {
    id: 'RockNext',
    name: 'RockNext Music Entertainment',
    fullLegalName: 'RockNext Music Entertainment™',
    org: 'RockNext Music Entertainment LLC',
    wlId: 'WL-002',
    tagline: 'Create. Mix. Master. Distribute.',
    mission: 'RockNext Music Entertainment™ is the ISRC Code Issuing body of Ad9x Holdings LLC and the music creation engine of JamZia Networks™. From first beat to final master, we give creators the tools to produce professional audio and reach global audiences. Infrastructure, CDN orchestration, and edge computing backbone.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#EC4899',
    secondaryColor: '#F43F5E',
    accentColor: '#F59E0B',
    bgGradient: 'linear-gradient(180deg, #0F0514 0%, #1A0A1E 50%, #140D20 100%)',
    icon: '♪',
    heroTitle: 'RockNext Music Entertainment™',
    heroSubtitle: 'ISRC Code Issuing body of Ad9x Holdings LLC — music creation & infrastructure',
    heroDescription: 'ISRC codes, music creation, mixing, mastering, and global distribution. Plus infrastructure backbone — CDN orchestration, edge computing, and validator nodes. Sister to BlackDiamond Networks™.',
    ctaPrimary: 'Start Creating',
    ctaPrimaryLink: '/audio',
    ctaSecondary: 'Live Stream',
    ctaSecondaryLink: '/live',
    stats: [
      { label: 'Tracks', value: '100M+' },
      { label: 'Creators', value: '50K+' },
      { label: 'Platforms', value: '100+' },
    ],
    platformFilter: ['Media', 'Finance'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  SkyLockr: {
    id: 'SkyLockr',
    name: 'SkyLockr',
    fullLegalName: 'SkyLockr™',
    org: 'SkyLockr Security Technologies',
    wlId: 'WL-003',
    tagline: 'Secure Everything. Store Forever.',
    mission: 'SkyLockr™ is the decentralized security and storage layer of JamZia Networks™. AES-256-GCM encryption, erasure-coded distribution across 22,000+ nodes, and immutable audit trails.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#3B82F6',
    secondaryColor: '#06B6D4',
    accentColor: '#8B5CF6',
    bgGradient: 'linear-gradient(180deg, #050F1E 0%, #0A1628 50%, #081830 100%)',
    icon: '🔒',
    heroTitle: 'SkyLockr™',
    heroSubtitle: 'the security backbone of JamZia Networks™',
    heroDescription: 'Decentralized storage with military-grade encryption. 99.95% availability. 80% cheaper than centralized alternatives. Your data, your control.',
    ctaPrimary: 'Secure Storage',
    ctaPrimaryLink: '/architecture',
    ctaSecondary: 'View Ledger',
    ctaSecondaryLink: '/ledger',
    stats: [
      { label: 'Nodes', value: '22K+' },
      { label: 'Data', value: '847 TB' },
      { label: 'Uptime', value: '99.95%' },
    ],
    platformFilter: ['World', 'Intel', 'Gov', 'Health'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  BlackDiamond: {
    id: 'BlackDiamond',
    name: 'BlackDiamond Networks',
    fullLegalName: 'BlackDiamond Networks™',
    org: 'BlackDiamond Networks LLC',
    wlId: 'WL-004',
    tagline: 'Media. Music. Distribution.',
    mission: 'BlackDiamond Networks™ is the parent company of BlackDiamond Media™ — the Rehearsal, Recording, Publishing and Distribution arm of Ad9x Holdings LLC. Sister company to RockNext Music Entertainment, the ISRC Code Issuing body of Ad9x Holdings LLC.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#1A1A1A',
    secondaryColor: '#C9A03F',
    accentColor: '#FFD700',
    bgGradient: 'linear-gradient(180deg, #0A0A0A 0%, #111111 50%, #1A1A1A 100%)',
    icon: '◆',
    heroTitle: 'BlackDiamond Networks™',
    heroSubtitle: 'parent of BlackDiamond Media™ — Rehearsal, Recording, Publishing & Distribution',
    heroDescription: 'BlackDiamond Media™: The complete media pipeline — from rehearsal to recording, publishing to global distribution. Sister to RockNext Music Entertainment, ISRC issuing body of Ad9x Holdings LLC.',
    ctaPrimary: 'Launch Campaign',
    ctaPrimaryLink: '/video',
    ctaSecondary: 'View Analytics',
    ctaSecondaryLink: '/architecture',
    stats: [
      { label: 'Platforms', value: '50+' },
      { label: 'Reach', value: 'Global' },
      { label: 'ROI', value: '3.2x avg' },
    ],
    platformFilter: ['Media', 'Finance', 'Intel'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  BlackDiamondStudios: {
    id: 'BlackDiamondStudios',
    name: 'BlackDiamond Studios',
    fullLegalName: 'BlackDiamond Studios™',
    org: 'BlackDiamond Media Group',
    wlId: 'WL-004B',
    tagline: 'Where Stories Come to Life.',
    mission: 'BlackDiamond Studios™ is the film and television production arm of BlackDiamond Media™. Full-service studio capabilities from development through distribution — original films, series, documentaries, and live event production.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#1A1A1A',
    secondaryColor: '#C9A03F',
    accentColor: '#FFD700',
    bgGradient: 'linear-gradient(180deg, #0A0A0A 0%, #111111 50%, #1A1A1A 100%)',
    icon: '🎬',
    heroTitle: 'BlackDiamond Studios™',
    heroSubtitle: 'the film & television production arm of JamZia Networks™',
    heroDescription: 'Full-service studio: development, production, post-production, and global distribution. Original films, series, documentaries, and live events.',
    ctaPrimary: 'View Productions',
    ctaPrimaryLink: '/boxflix',
    ctaSecondary: 'Submit Pitch',
    ctaSecondaryLink: '/connect',
    stats: [
      { label: 'Originals', value: '120+' },
      { label: 'Films', value: '85+' },
      { label: 'Awards', value: '24' },
    ],
    platformFilter: ['Media', 'Finance', 'Intel'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  BlackDiamondRecords: {
    id: 'BlackDiamondRecords',
    name: 'BlackDiamond Records',
    fullLegalName: 'BlackDiamond Records™',
    org: 'BlackDiamond Media Group',
    wlId: 'WL-004C',
    tagline: 'Sound Without Limits.',
    mission: 'BlackDiamond Records™ is the music label and audio production division of BlackDiamond Media™. Artist development, recording, mixing, mastering, and global distribution across all major platforms.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#1A1A1A',
    secondaryColor: '#C9A03F',
    accentColor: '#FFD700',
    bgGradient: 'linear-gradient(180deg, #0A0A0A 0%, #111111 50%, #1A1A1A 100%)',
    icon: '♪',
    heroTitle: 'BlackDiamond Records™',
    heroSubtitle: 'the music label of JamZia Networks™',
    heroDescription: 'Artist development, recording studios, mixing, mastering, and global distribution. From first demo to platinum album.',
    ctaPrimary: 'Listen Now',
    ctaPrimaryLink: '/music',
    ctaSecondary: 'Submit Demo',
    ctaSecondaryLink: '/connect',
    stats: [
      { label: 'Artists', value: '200+' },
      { label: 'Albums', value: '500+' },
      { label: 'Streams', value: '2.1B+' },
    ],
    platformFilter: ['Media', 'Finance'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  BlackDiamondPublishing: {
    id: 'BlackDiamondPublishing',
    name: 'BlackDiamond Publishing',
    fullLegalName: 'BlackDiamond Publishing™',
    org: 'BlackDiamond Media Group',
    wlId: 'WL-004D',
    tagline: 'Words That Change Worlds.',
    mission: 'BlackDiamond Publishing™ is the book publishing, digital content, and educational materials division of BlackDiamond Media™. Print, digital, and audiobook distribution with global reach.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#1A1A1A',
    secondaryColor: '#C9A03F',
    accentColor: '#FFD700',
    bgGradient: 'linear-gradient(180deg, #0A0A0A 0%, #111111 50%, #1A1A1A 100%)',
    icon: '📖',
    heroTitle: 'BlackDiamond Publishing™',
    heroSubtitle: 'the publishing arm of JamZia Networks™',
    heroDescription: 'Book publishing, digital content, and educational materials. Print, ebook, and audiobook distribution to global retailers.',
    ctaPrimary: 'Browse Catalog',
    ctaPrimaryLink: '/shop',
    ctaSecondary: 'Submit Manuscript',
    ctaSecondaryLink: '/connect',
    stats: [
      { label: 'Titles', value: '1,200+' },
      { label: 'Authors', value: '350+' },
      { label: 'Languages', value: '18' },
    ],
    platformFilter: ['Media', 'Intel'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  Conduit: {
    id: 'Conduit',
    name: 'Conduit Capital AI',
    fullLegalName: 'Conduit Capital AI™',
    org: 'Conduit Capital AI Advisory',
    wlId: 'WL-005',
    tagline: 'Institutional DeFi. Advisory Excellence.',
    mission: 'Conduit Capital AI™ is the institutional banking and Web3 DeFi advisory arm of JamZia Networks™. Tokenomics design, liquidity strategy, market making, and regulatory navigation for accredited investors.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#10B981',
    secondaryColor: '#34D399',
    accentColor: '#059669',
    bgGradient: 'linear-gradient(180deg, #05140A 0%, #0A1F14 50%, #0D2818 100%)',
    icon: '⚡',
    heroTitle: 'Conduit Capital AI™',
    heroSubtitle: 'the institutional advisory arm of JamZia Networks™',
    heroDescription: 'Tokenomics, liquidity strategy, market making, and DeFi products for institutional clients. Exclusive banking partnerships with custody, OTC, and staking-as-a-service.',
    ctaPrimary: 'Explore DeFi',
    ctaPrimaryLink: '/dex',
    ctaSecondary: 'View Architecture',
    ctaSecondaryLink: '/architecture',
    stats: [
      { label: 'AUM', value: '$2.4B' },
      { label: 'Clients', value: '180+' },
      { label: 'APY', value: '8-12%' },
    ],
    platformFilter: ['Finance', 'Gov', 'Intel'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  RiverShyre: {
    id: 'RiverShyre',
    name: 'RiverShyre',
    fullLegalName: 'RiverShyre™',
    org: 'RiverShyre Interactive Entertainment',
    wlId: 'WL-006',
    tagline: 'Play. Explore. Create Worlds.',
    mission: 'RiverShyre™ is the AR, gaming, and interactive entertainment platform of JamZia Networks™. Unity and Unreal integration, WebXR, spatial computing, and real-time multiplayer synchronization.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#8B5CF6',
    secondaryColor: '#A78BFA',
    accentColor: '#F59E0B',
    bgGradient: 'linear-gradient(180deg, #0F051E 0%, #1A0F2E 50%, #140D30 100%)',
    icon: '🎮',
    heroTitle: 'RiverShyre™',
    heroSubtitle: 'the interactive entertainment arm of JamZia Networks™',
    heroDescription: 'AR experiences, cloud gaming, and immersive worlds. AI-generated game assets, NFT-based item ownership, and tournament prize distribution via XRPL.',
    ctaPrimary: 'Enter the Game',
    ctaPrimaryLink: '/battle',
    ctaSecondary: 'Explore AR',
    ctaSecondaryLink: '/ar',
    stats: [
      { label: 'Games', value: '200+' },
      { label: 'Players', value: '84K+' },
      { label: 'Tournaments', value: '1,200+' },
    ],
    platformFilter: ['Media', 'World', 'Health'],
    showCrisisBanner: false,
    showCottonBrickRoad: true,
    showJamRep: true,
  },

  Collective: {
    id: 'Collective',
    name: 'Collective General',
    fullLegalName: 'Collective General Technologies™',
    org: 'Collective General Technologies',
    wlId: 'WL-007',
    tagline: 'Infrastructure That Scales.',
    mission: 'Collective General Technologies™ is the cloud infrastructure and backend operations arm of JamZia Networks™. Validator nodes, orchestrator networks, storage coordination, and AI compute clusters — 24/7 NOC monitoring.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#6B7280',
    secondaryColor: '#9CA3AF',
    accentColor: '#F59E0B',
    bgGradient: 'linear-gradient(180deg, #0A0A0A 0%, #141414 50%, #1A1A1E 100%)',
    icon: '⚙️',
    heroTitle: 'Collective General™',
    heroSubtitle: 'the infrastructure arm of JamZia Networks™',
    heroDescription: 'Cloud orchestration, node management, API gateways, and 24/7 NOC. Kubernetes, auto-scaling, multi-region active-active — 99.99% uptime SLA.',
    ctaPrimary: 'View Architecture',
    ctaPrimaryLink: '/architecture',
    ctaSecondary: 'View Ledger',
    ctaSecondaryLink: '/ledger',
    stats: [
      { label: 'Nodes', value: '50K+' },
      { label: 'Uptime', value: '99.99%' },
      { label: 'Regions', value: '12' },
    ],
    platformFilter: ['Gov', 'Intel', 'Health'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  WisdomPay: {
    id: 'WisdomPay',
    name: 'WisdomPay',
    fullLegalName: 'WisdomPay™',
    org: 'WisdomPay Financial Services',
    wlId: 'WL-008',
    tagline: 'Borderless Payments. Instant Settlement.',
    mission: 'WisdomPay™ is the payment subsidiary of JamZia Networks™. Built on XRP Ledger — instant settlement in 3-5 seconds, fees under a penny. Cross-border remittance, subscription billing, and micropayments for all 50+ platforms.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#06B6D4',
    secondaryColor: '#22D3EE',
    accentColor: '#0891B2',
    bgGradient: 'linear-gradient(180deg, #05141A 0%, #0A1F28 50%, #0D2830 100%)',
    icon: '💳',
    heroTitle: 'WisdomPay™',
    heroSubtitle: 'the payment engine of JamZia Networks™',
    heroDescription: 'Cross-border payments on XRP Ledger. 3-5 second settlement. Sub-penny fees. SkyIvy and SkyLockr tokens. Wallet, checkout, and disbursement for all 50+ platforms.',
    ctaPrimary: 'Open Wallet',
    ctaPrimaryLink: '/pay',
    ctaSecondary: 'View Transactions',
    ctaSecondaryLink: '/credits',
    stats: [
      { label: 'Transactions', value: '15K+' },
      { label: 'Settlement', value: '3-5s' },
      { label: 'Fee', value: '<$0.01' },
    ],
    platformFilter: ['Finance', 'Gov', 'Health'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  Ad9x: {
    id: 'Ad9x',
    name: 'Ad9x Media',
    fullLegalName: 'Ad9x Media™',
    org: 'Ad9x Holdings LLC',
    wlId: 'WL-009',
    tagline: 'Advertising That Works. Everywhere.',
    mission: 'Ad9x Media™ is the advertising and marketing engine of JamZia Networks™. Contextual targeting across 50+ platforms, cross-platform attribution, brand safety scoring, and real-time ROI — privacy-first by design.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#EF4444',
    secondaryColor: '#F87171',
    accentColor: '#DC2626',
    bgGradient: 'linear-gradient(180deg, #1A0505 0%, #280A0A 50%, #1E0A0A 100%)',
    icon: '📢',
    heroTitle: 'Ad9x Media™',
    heroSubtitle: 'the advertising arm of JamZia Networks™',
    heroDescription: 'Reach audiences across 50+ platforms with AI-optimized campaigns. Contextual targeting, cross-platform attribution, and brand safety scoring. Privacy-first.',
    ctaPrimary: 'Launch Campaign',
    ctaPrimaryLink: '/video',
    ctaSecondary: 'View Inventory',
    ctaSecondaryLink: '/architecture',
    stats: [
      { label: 'Platforms', value: '50+' },
      { label: 'Impressions', value: '2.1B+' },
      { label: 'CTR', value: '4.8%' },
    ],
    platformFilter: ['Media', 'Finance', 'Intel'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  Ad9xPharma: {
    id: 'Ad9xPharma',
    name: 'Ad9x Pharmaceuticals',
    fullLegalName: 'Ad9x Pharmaceuticals™',
    org: 'Ad9x Holdings LLC',
    wlId: 'WL-010',
    tagline: 'Health Innovation. Accessible Care.',
    mission: 'Ad9x Pharmaceuticals™ is the healthcare and pharmaceutical division of Ad9x Holdings LLC. Digital health platforms, telemedicine integration, pharmaceutical research coordination, and patient care management systems.',
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#059669',
    secondaryColor: '#10B981',
    accentColor: '#34D399',
    bgGradient: 'linear-gradient(180deg, #05140E 0%, #0A1F18 50%, #0D2820 100%)',
    icon: '⚕️',
    heroTitle: 'Ad9x Pharmaceuticals™',
    heroSubtitle: 'the healthcare innovation arm of JamZia Networks™',
    heroDescription: 'Digital health platforms, telemedicine, pharmaceutical research coordination, and patient care management. Bridging technology and healthcare for better outcomes.',
    ctaPrimary: 'Explore Health',
    ctaPrimaryLink: '/health',
    ctaSecondary: 'Research Portal',
    ctaSecondaryLink: '/architecture',
    stats: [
      { label: 'Partners', value: '120+' },
      { label: 'Patients', value: '500K+' },
      { label: 'Research', value: '45 Active' },
    ],
    platformFilter: ['Health', 'Gov', 'Intel'],
    showCrisisBanner: false,
    showCottonBrickRoad: false,
    showJamRep: true,
  },

  MrsCotton: {
    id: 'MrsCotton',
    name: "Mrs Cotton's Academy",
    fullLegalName: "Mrs Cotton's Academy™",
    org: 'Ad9x Holdings LLC',
    wlId: 'WL-011',
    tagline: 'Education That Inspires. Knowledge That Lasts.',
    mission: "Mrs Cotton's Academy™ is the premier educational institution of JamZia Networks™. 29 grade levels from Nursery to Doctoral, Phonics Mastery, report cards every 6 weeks, GPA tracking, and a gas/brick economy that makes learning rewarding.",
    poweredBy: 'Powered by JamZia Networks™',
    copyright: '(c) 2026 Ad9x Holdings LLC - a Georgia Limited Liability Company',
    primaryColor: '#8B5CF6',
    secondaryColor: '#A78BFA',
    accentColor: '#C4B5FD',
    bgGradient: 'linear-gradient(180deg, #1E1B4B 0%, #312E81 50%, #1E1B4B 100%)',
    icon: '🎓',
    heroTitle: "Mrs Cotton's Academy™",
    heroSubtitle: 'the educational heart of JamZia Networks™',
    heroDescription: '29 grade levels from Nursery to Doctoral. Phonics Mastery, 6-week report cards, GPA, credit hours, and a gas/brick economy. Learning that rewards you.',
    ctaPrimary: 'Start Learning',
    ctaPrimaryLink: '/learn',
    ctaSecondary: 'View Courses',
    ctaSecondaryLink: '/learn',
    stats: [
      { label: 'Grade Levels', value: '29' },
      { label: 'Courses', value: '500+' },
      { label: 'Students', value: '100K+' },
    ],
    platformFilter: ['Healing', 'Media', 'Finance', 'World', 'Intel', 'Gov', 'Health'],
    showCrisisBanner: false,
    showCottonBrickRoad: true,
    showJamRep: true,
  },
};

export function getBrandById(id: string): WLBrand | undefined {
  return WL_BRANDS[id as BrandId];
}

export const BRAND_IDS: BrandId[] = Object.keys(WL_BRANDS) as BrandId[];
